name: Deploy to Tencent COS
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-18.04
    env:
      COS_SECRET_ID: ${{ secrets.COS_SECRET_ID }}
      COS_SECRET_KEY: ${{ secrets.COS_SECRET_KEY }}
      COS_TARGET_BUCKET: ${{ secrets.COS_TARGET_BUCKET }}
      COS_BUCKET_REGION: ${{ secrets.COS_BUCKET_REGION }}
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          yarn
          yarn build

      - name: Deploy
        run: node deploy.js
